# .github/workflows/update-rentals.yml
name: update-rentals

on:
  push:                # fires on every push to main
    branches: [main]
  workflow_dispatch:   # gives you a UI "Run workflow" button
  schedule:
    - cron: '0 6 * * *'   # daily 06:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # needed for auto‑commit

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: run scraper
        env:
          RAPIDAPI_KEY: ${{secrets.RAPIDAPI_KEY}}
        run: |
          node - <<'NODE'
          import { mkdir, writeFile } from 'fs/promises';

          const key = process.env.RAPIDAPI_KEY;
          if (!key) { console.error('RAPIDAPI_KEY missing'); process.exit(1); }

          const url = 'https://priceline-com2.p.rapidapi.com/cars/search?pickUpLocation=JFK&dropOffLocation=JFK&pickUpDate=2025-06-01&pickUpTime=10:00&dropOffDate=2025-06-04&dropOffTime=10:00';

          const res = await fetch(url, {
            headers: {
              'x-rapidapi-key': key,
              'x-rapidapi-host': 'priceline-com2.p.rapidapi.com'
            }
          });

          if (!res.ok) { console.error(res.statusText); process.exit(1); }

          const json = await res.json();
          const data = json?.cars?.results ?? [];
          await mkdir('data', { recursive: true });
          await writeFile('data/rentals.json', JSON.stringify(data, null, 2));
          console.log(`Wrote ${data.length} records`);
          NODE

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update rentals.json'
          file_pattern:   'data/rentals.json'
